# Generated by Django 4.2 on 2025-08-10 20:07

from django.db import migrations, models
import django.db.models.deletion
import dynamic_forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', dynamic_forms.models.ResponseField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('form_definition', dynamic_forms.models.FormField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticketprocess',
            name='form_definition',
        ),
        migrations.DeleteModel(
            name='FormDefinition',
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ticketflow.formtemplate'),
        ),
        migrations.AddField(
            model_name='ticketprocess',
            name='form_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ticketflow.formtemplate'),
        ),
    ]
