# Generated by Django 4.2 on 2025-08-10 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketflow', '0002_formsubmission_formtemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketprocess',
            name='form_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketflow.formtemplate'),
        ),
    ]
