# Generated by Django 4.2 on 2025-08-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketflow', '0003_alter_ticketprocess_form_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplate',
            name='form_definition',
            field=models.JSONField(default=dict),
        ),
    ]
