# Generated by Django 4.2 on 2025-08-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketflow', '0004_alter_formtemplate_form_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplate',
            name='form_definition',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
