# Generated by Django 4.2 on 2025-08-10 22:53

from django.db import migrations
import dynamic_forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketflow', '0005_alter_formtemplate_form_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='response',
            field=dynamic_forms.models.ResponseField(default=dict),
        ),
    ]
