# Generated by Django 4.2 on 2025-08-11 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketflow', '0006_alter_formsubmission_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='ticketprocess',
            name='form_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ticketflow.formtemplate'),
        ),
    ]
