# Generated by Django 4.2 on 2025-08-12 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketflow', '0007_alter_formsubmission_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notify_emails', models.TextField(blank=True, help_text='Comma-separated emails to notify when this form is submitted')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ticketflow.form')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormEntryValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True)),
                ('value_file', models.FileField(blank=True, null=True, upload_to='form_uploads/')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='ticketflow.formentry')),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Long text'), ('select', 'Drop-down'), ('file', 'File upload')], default='text', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('choices', models.TextField(blank=True, help_text='For "Drop-down": write options separated by commas, e.g. "Low, Medium, High"')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='ticketflow.form')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='ticketprocess',
            name='form_template',
        ),
        migrations.DeleteModel(
            name='FormSubmission',
        ),
        migrations.DeleteModel(
            name='FormTemplate',
        ),
        migrations.AddField(
            model_name='formentryvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketflow.formfield'),
        ),
        migrations.AddField(
            model_name='ticketprocess',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ticketflow.form'),
        ),
    ]
