# Generated by Django 4.2 on 2025-08-12 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketflow', '0008_form_formentry_formentryvalue_formfield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketprocess',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ticketflow.form'),
            preserve_default=False,
        ),
    ]
