# Generated by Django 4.2 on 2025-08-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketflow', '0011_alter_formfield_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='choices',
            field=models.TextField(blank=True, help_text='For "Drop-down": write options separated by commas, e.g. "Low, Medium, High"'),
        ),
    ]
