# Generated by Django 4.2 on 2025-08-19 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketflow', '0012_alter_formfield_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='role',
            field=models.CharField(choices=[('user', 'User/Requester'), ('dev', 'Developer'), ('ba', 'Business Analyst'), ('pm', 'Project Manager')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='ticketprocess',
            name='entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_process', to='ticketflow.formentry'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='choices',
            field=models.TextField(blank=True, help_text='For "Drop-down": comma-separated options'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Long text'), ('select', 'Drop-down'), ('file', 'File upload'), ('email', 'Email'), ('date', 'Date (YYYY-MM-DD)'), ('number', 'Number')], default='text', max_length=20),
        ),
    ]
