# Generated by Django 4.2 on 2025-08-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketflow', '0013_formfield_role_ticketprocess_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='default_value',
            field=models.CharField(blank=True, default='', help_text='Default text/value', max_length=200),
        ),
        migrations.AddField(
            model_name='formfield',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Hide field in forms (but store value if present)'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='max_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='min_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='placeholder',
            field=models.CharField(blank=True, default='', help_text='Placeholder for inputs', max_length=200),
        ),
        migrations.AddField(
            model_name='formfield',
            name='readonly',
            field=models.BooleanField(default=False, help_text='Show as read-only'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='regex',
            field=models.CharField(blank=True, default='', help_text='Optional regex validation', max_length=200),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='choices',
            field=models.TextField(blank=True, help_text='For "Drop-down/Radio": comma-separated options'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Long text'), ('select', 'Drop-down'), ('file', 'File upload'), ('email', 'Email'), ('date', 'Date (YYYY-MM-DD)'), ('number', 'Number'), ('checkbox', 'Checkbox'), ('radio', 'Radio')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='role',
            field=models.CharField(choices=[('user', 'Risk Representative'), ('dev', 'Risk Champion'), ('ba', 'Risk Approver'), ('pm', 'CRO')], default='user', max_length=10),
        ),
    ]
